### ISSUE TITLE
Build fails if non-anomaly project used

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/example-standalone-inferencing-espressif-esp32#6]
If you import an Edge Impulse project without anomaly detection, there is no *edge-impulse-sdk/anomaly* directory. As a result, you will get the following error if you try to build:

```
CMake Error at /Users/sgmustadio/esp/esp-idf/tools/cmake/component.cmake:307 (message):
  Include directory
  '/Users/sgmustadio/Projects/GitHub/research-mlsys2023-timing-tests/timing-tests-esp32/edge-impulse-sdk/anomaly'
  is not a directory.
Call Stack (most recent call first):
  /Users/sgmustadio/esp/esp-idf/tools/cmake/component.cmake:480 (__component_add_include_dirs)
  main/CMakeLists.txt:49 (idf_component_register)
```

The workaround is to comment out `${EI_SDK_FOLDER}/anomaly` in *main/CMakeLists.txt*. The proposed fix would be to import the *edge-impulse-sdk* without explicitly calling each folder (e.g. include *edge-impulse-sdk/cmake/zephyr/CMakeLists.txt*).

**Comment by AIWintermuteAI** [comment]
Actually it is not related to absence or presence of anomaly model, but rather to multi-model PR changes.
Fixed by https://github.com/edgeimpulse/example-standalone-inferencing-espressif-esp32/commit/e14df0d98559edd45044ced6390d92288375855c.
Let me know if that solved the issue for you.

**Comment by ShawnHymel** [comment]
Verified--the changes to CMakeLists.txt and `#include "edge-impulse-sdk/classifier/ei_run_classifier.h"` work on my end.
